import 'package:flutter/material.dart';
import '../app_strings.dart';
import '../core/draft_store.dart';
import '../core/settings.dart';

class SettingsScreen extends StatelessWidget { const SettingsScreen({required this.settings,super.key});final AppSettings settings;
  @override Widget build(BuildContext context){final s=S.of(context);return Scaffold(appBar:AppBar(title:Text(s.t('Settings','การตั้งค่า'))),body:ListView(padding:const EdgeInsets.all(20),children:[
    DropdownButtonFormField<String>(initialValue:settings.locale?.languageCode??'system',decoration:InputDecoration(labelText:s.t('Language','ภาษา')),items:[DropdownMenuItem(value:'system',child:Text(s.t('System','ตามระบบ'))),const DropdownMenuItem(value:'en',child:Text('English')),const DropdownMenuItem(value:'th',child:Text('ไทย'))],onChanged:(v)=>settings.setLocale(v=='system'?null:Locale(v!))),const SizedBox(height:16),
    DropdownButtonFormField<ThemeMode>(initialValue:settings.themeMode,decoration:InputDecoration(labelText:s.t('Theme','ธีม')),items:ThemeMode.values.map((v)=>DropdownMenuItem(value:v,child:Text(s.t(v.name,v==ThemeMode.system?'ตามระบบ':v==ThemeMode.light?'สว่าง':'มืด')))).toList(),onChanged:(v)=>settings.setTheme(v!)),const SizedBox(height:28),
    Text(s.t('Privacy','ความเป็นส่วนตัว'),style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:8),Text(s.t('Documents, drafts, and settings stay in private app storage. Processing is on-device and no content analytics, account, backend, or upload is used. Your operating system may include app data in device backups according to its settings. QR history is not stored.','เอกสาร ฉบับร่าง และการตั้งค่าอยู่ในพื้นที่ส่วนตัวของแอป การประมวลผลทำในเครื่อง ไม่มีการวิเคราะห์เนื้อหา บัญชี เซิร์ฟเวอร์ หรือการอัปโหลด ระบบปฏิบัติการอาจรวมข้อมูลแอปในการสำรองข้อมูลตามการตั้งค่า และไม่มีการเก็บประวัติคิวอาร์')),const SizedBox(height:24),
    OutlinedButton.icon(onPressed:()async{final confirmed=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:Text(s.t('Delete all documents?','ลบเอกสารทั้งหมดหรือไม่')),content:Text(s.t('This cannot be undone.','ไม่สามารถย้อนกลับได้')),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:Text(MaterialLocalizations.of(c).cancelButtonLabel)),FilledButton(onPressed:()=>Navigator.pop(c,true),child:Text(s.t('Delete','ลบ')))]));if(confirmed==true){for(final d in await DraftStore().loadAll()){await DraftStore().delete(d.id);}if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s.t('Local documents deleted','ลบเอกสารในเครื่องแล้ว'))));}},icon:const Icon(Icons.delete_forever_outlined),label:Text(s.t('Delete all local documents','ลบเอกสารในเครื่องทั้งหมด')))
  ]));}}
